### ISSUE TITLE
Bootstrap Implementation

### ISSUE THREAD

**Issue by jake-burton29** [Net-Tech-Inc-LLC/graceShopper#18]
Decide as a team on:

- [x]  CSS Framework - (bootstrap)
- [x] Color Scheme
- [x] Logo
- [x] Company Goal

**Comment by sarinjthorn** [comment]
Bootstrap? Tailwind?

**Comment by sarinjthorn** [comment]
Bootstrap: attempting to implement now

**Comment by sarinjthorn** [comment]
Added bootstrap for NavBar, and Carousel on Homepage.

**Comment by sarinjthorn** [comment]
deleted comment

**Comment by sarinjthorn** [comment]
deleted comment
