### ISSUE TITLE
Component: ShoppingCart

### ISSUE THREAD

**Issue by jake-burton29** [Net-Tech-Inc-LLC/graceShopper#28]
- [x] + / - buttons for changing quantity
- [x] Set maximum for inventory in stock
- [x] Set minimum 1
- [x] Remove from cart button
- [x] Remove all from cart
- [x] Display Total based on product prices
- [x] Checkout button -> Checkout page

**Comment by sarinjthorn** [comment]
shopping cart comments made by Pawan during code review on 8/17/22 may be helpful:
(store an object with some data (id, quantity) to the front end for the cart maybe) works for guest cart persisting (hash map?)

productorders.js in axios services is where we add methods to add things to cart
